import React from 'react';
import '../../App.css';
import './Blogpage.css';

import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';


function FridayHarbor() {
  return (
    <>
      <Navbar />
        <div className='title'>
          <h1>San Juan Island: Slug, Hemlock, Mushroom, and the Pig War</h1>
        </div>

        <article>
            <p>San Juan Islands in deep fall are said to be the best time to visit. The weather is cooler, and the island towns slow down after the summer visitors, clearing out the benches and docks to welcome seagulls arriving from all corners of the Puget Sound. Earlier this month, I visited the University of Washington’s Friday Harbor Lab, located on San Juan Island.</p>
            <p>The rain was pouring the moment we got off the ferry from Anacortes to Friday Harbor, one of the largest towns on the San Juan Islands. “Crap,” said Mary, one of my colleagues at UW Sustainability, who traveled with me this time. “Looks like the morning hike isn’t going to happen.” Sharing a common love for outdoor activities and nature, the first thing on our agenda was unsurprisingly a hike through San Juan Island National Historic Park, located at the southern tip of the island. Despite the rain, we still drove to the trailhead to try our luck. The trailhead was just 10 minutes from the ferry terminal by car or, if the weather permits, a 25-minute scenic bike ride away. Luckily, the clouds showed us some mercy when we arrived and the pouring rain turned into drizzles. The situation only got better once we stepped onto the trail. On both sides of the path stood countless Western Hemlocks. In my opinion, they were almost the perfect trees for providing everything beneath them shelter from the rain. Though their leaves were neither waxy nor large, their needle-like structure provided a large surface area and plenty of friction for a thick layer of moss to attach to firmly. Together, they acted like huge green towels hanging on the Hemlocks’ straight branches, soaking up all the rainwater from above. Conveniently, the moss was concentrated higher up on the upper sections of those 100-foot-plus Hemlocks. On the lower half of the trees, there was almost nothing obstructing the view or the trail, giving us plenty of clearance to pass through.</p>
            <img src='asset/images/IMG_2522.jpg'/>
            <p>The Western Hemlocks welcomed us, but they also offered a sheltered growing space for fungi, grass, and any other plants lower than them. Somethings that caught our eyes were the mushrooms, popping up from every imaginable corner in the forest: in front of the rocks, below the bushes, on top of the tree stumps. I was no expert on mushrooms, so I always tried to keep a safe distance and not disturb the potentially toxic ones. The truth is, I had no idea how to tell whether a mushroom is edible or not, so the safest option was to avoid touching any of them. Even if they look harmless, with no colorful dots and a neutral brownish base color, I suspected they might be mimicking the store-bought mushrooms while secretly being deadly underneath. I supposed every human who ever set foot on this land and claimed it as theirs wasn’t brave enough to risk their life for the mushrooms. That’s why the mushrooms could simply exist here, as if the world around them had always remained unchanged.</p>
            <p>I found someone who is more knowledgeable about mushrooms, though—a slug. Sitting on top of a white mushroom that had been flipped upside down, the slug was primarily dark yellow, with speckles of black on its back. The colors were sealed behind the gel-like texture of the skin, staying consistent and matte under different lighting conditions, much like how mushrooms blend in with the weeds and soil. This color combination made the finger-size slug somewhat hard to spot, and we almost stepped straight on. The slug curled up the middle part of its body on the stem of the mushroom while resting the other parts of its body mid air, like how humans sit on a hammock. The entire time we were observing, the slug moved so little. Some of us suggested poking the squishy-looking back with a stick to see if the slug had mistakenly eaten the wrong mushroom, but I had faith in that slug. I felt that the slug was definitely more confident than I was when it came to distinguishing different types of mushrooms. Otherwise, who would have the boldness to take a comfortable lunch nap right on top? I convinced everyone to leave the slug alone as if we had never been there, so the slug could enjoy a peaceful lunch undisturbed.</p>
            <p>The trail led us to the peak of Mount Finlayson, the highest point on San Juan Island. As I stood atop Mount Finlayson, my phone buzzed with a message: “Welcome to Canada.” I hadn’t realized how close we were to the border. Gazing into the distance, I could see Victoria, Canada, right across the strait, protruding into the south of the San Juan Island. “Do y’all know why the US-Canada border is so weirdly shaped around the San Juan Islands?” Mary prompted the group, “It’s because of the Pig War.” The Oregon Treaty, established in 1846, set the forty-ninth parallel as the border between Britain and the United States. However, because of the ambiguity of the original treaty, both countries claimed the right to settle on the San Juan Islands. Over time, the islands’ natural resources attracted settlers from both sides, who opened ranches and farms. Thirteen years later, in 1859, a border dispute erupted between the United States and Britain over sovereignty of San Juan Island. Funny enough, the trigger of the dispute was a pig. Lyman Cutlar, an American who settled on the south end of the island close to the foot of Mount Finlayson, shot and killed a pig that had wandered onto his farm from a British sheep ranch on the north-side of the island and started rooting in his garden. British authorities then threatened to arrest Lyman and evict all Americans from the island. This dispute soon escalated into a military standoff. Both countries dispatched troops to the island and built camps, with the British taking the north and the Americans the south. This divided situation lasted until the 1870s when the United States gained international recognition of sovereignty over the entire San Juan Islands, and the last U.S. marine left the American camp on the island a few years after the withdrawal of all British marines. The reason this conflict is called “The Pig War” is because the only casualty was the pig. The San Juan Island National Historic Park was later established to preserve the original site of the American camp during the Pig War and educate visitors about the history behind the land.</p>
            <p>The war had long passed and by the time I visited the island, there was no sign of division between the north and south. The Western Hemlocks had equally protected all species on the island from the rain for millennia; The slug knew if a mushroom was safe to eat regardless of which side of the island the mushroom grew on; The unfortunate pig that was shot in 1859 still couldn’t tell the difference between British lettuce and American lettuce. On this island, everything had returned to a state of peace, as though humans had never been here. In fact, everything remained peaceful because we intentionally chose not to disturb it—because we never knew if the next mushroom we picked up would be the toxic one, or if chopping down the Hemlocks would leave the slugs, mushrooms, and even humans without shelter from the rain.</p>
            <p>Before heading down to the trailhead, I looked back in the direction of Canada. “Is everything still just as peaceful across the strait?” “Is there a slug on that island enjoying a delicious meal as well?” I would never know the answer to these questions without crossing the border. But I had learned from my years of work with sustainability and environmental policy that, unlike the U.S., which has the Northwest forest plan protecting old growth, Canada doesn’t have similar policies in place. So, the Western Hemlocks on the other side of the strait may already have been chopped down, replaced by trees with no moss on them. Hikers on the other side might be out of luck if they want to spot a slug indulging a mushroom on a rainy day.</p>
            <p>The rain drizzled nonstop for the entire first day we were on San Juan Island. I bet the people living across the U.S.-Canada border had to gear up for the weather, too. It slowly dawned on me how sad it is that people are willing to start wars over nature, as if we can possess its real value, as if we can own a slug simply enjoying its mushroom. Perhaps the only piece of nature we can own but refuse to acknowledge is that if it rains on my side, it rains on your side as well.</p>

            
        </article>
      <Footer />
    </>
  );
}

export default FridayHarbor;